#!/bin/bash

TD=tmpdir

TF_UTF8F=arvizturo_utf8latin2_vegyes.txt
TF_UCSX="$TD/arvizturo_utf8latin2_vegyes_ucsx.txt"
TF_UTF8F_UCSX="$TD/arvizturo_r_utf8latin2_vegyes.txt"

mkdir -p "$TD"

if ! m; then
   echo "Compile error"
   exit 1
fi

bin/utf8f2ucsx_latin2 <"$TF_UTF8F" >"$TF_UCSX"
bin/ucsx2utf8f <"$TF_UCSX" >"$TF_UTF8F_UCSX"

if cmp "$TF_UTF8F" "$TF_UTF8F_UCSX"; then
   # echo "$?"
   echo "$0: OK"
else
   echo "$?"
   echo "$0: error"
fi 

