#!/bin/bash

TD=tmpdir

TF_UTF8F_MIXED=arvizturo_latin2.txt
TF_UTF8F=arvizturo.txt
TF_UCSX="$TD/arvizturo_latin2_ucsx.txt"
TF_UTF8F_UCSX="$TD/arvizturo_r_latin2.txt"

mkdir -p "$TD"

if ! m; then
   echo "Compile error"
   exit 1
fi

bin/utf8f2ucsx --utf8fmixedlatin2 <"$TF_UTF8F_MIXED" >"$TF_UCSX"
bin/ucsx2utf8f <"$TF_UCSX" >"$TF_UTF8F_UCSX"

if cmp "$TF_UTF8F" "$TF_UTF8F_UCSX"; then
   # echo "$?"
   echo "$0: OK"
else
   echo "$?"
   echo "$0: error"
fi 

