#!/bin/sh

# Write dependencies to the Makefile.

MAKEFILE=Makefile
gcc -MM -I.. ../*.c *.c | 
   cutnpaste $MAKEFILE '# Start depends by mdep2make' '# End depends by mdep2make' |
   updatewrite $MAKEFILE
