#!/bin/bash

TD=tmpdir

TF=ucsxtest.txt
TMPF="$TD/ucsxtest-t.txt"

mkdir -p "$TD"

m

bin/tcr >"$TMPF"

if [ ! -f "$F" ]; then
   mv "$TMPF" "$TF"
elif cmd "$TF" "$TMPF"; then
   rm -rf "$TF"
   mv "$TMPF" "$TF"
fi

