#!/bin/bash

# utf8->latin2->utf8

#set -x
TD=tmpdir

TF_START=arvizturo2_vegyes.txt
TF_EXPECTED_RESULT=arvizturo2_utf8.txt
TF_R_UTF8="$TD/arvizturo2_r_utf8.txt"
TF_RESULT="$TF_R_UTF8"

mkdir -p "$TD"

if ! m; then
   echo "Compile error"
   exit 1
fi

bin/utf8fmixedlatin2full2utf8f <"$TF_START" >"$TF_R_UTF8"

if cmp "$TF_RESULT" "$TF_EXPECTED_RESULT"; then
   # echo "$?"
   echo "$0: OK"
else
   echo "$?"
   echo "$0: error"
fi 

